name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  deploy-to-test:
    name: Deploy To Test Env
    runs-on: ubuntu-latest
    steps:

    - id: get-changed-files
      uses: lots0logs/gh-action-get-changed-files@2.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get SF changed files
      id: sf-changed-files
      uses: danishwilliams/sfdx-files-github-action@v1.4
      with:
        changed-files: ${{ steps.get-changed-files.outputs.modified }}
        added-files: ${{ steps.get-changed-files.outputs.added }}
        renamed-files: ${{ steps.get-changed-files.outputs.renamed }}

    - name: Checkout
      uses: actions/checkout@v2

    - uses: sfdx-actions/setup-sfdx@v1
      with:
        sfdx-auth-url: ${{ secrets.DEV_SANDBOX_AUTH }}
        
    - name: Deploy
      run: sfdx force:source:deploy --sourcepath "${{steps.sf-changed-files.outputs.files-to-deploy}}" --testlevel RunSpecifiedTests --runtests "${{steps.sf-changed-files.outputs.test-files}}"
        